name: CI

on: [push, pull_request]

jobs:
  format:
    name: stylua
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Format
        uses: JohnnyMorganz/stylua-action@v3
        with:
          version: 0.17.1
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always --check lua/

  tests:
    name: tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nvim: [v0.9.0, nightly]

    steps:
      - uses: actions/checkout@v3

      - name: Set Envs
        run: |
          echo "VIM=~/.local/share/nvim/share/nvim/runtime" >> $GITHUB_ENV
          echo "PATH=~/.local/share/nvim/bin:$PATH" >> $GITHUB_ENV

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.local/share/nvim
          key: ${{ runner.os }}-nvim-${{ matrix.nvim }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.local/share/nvim/
          curl -sL "https://github.com/neovim/neovim/releases/download/${{ matrix.nvim }}/nvim-linux64.tar.gz" | tar xzf - --strip-components=1 -C ~/.local/share/nvim/
          git clone --depth 1 https://github.com/nvim-treesitter/nvim-treesitter.git ~/.local/share/nvim/site/pack/vendor/start/nvim-treesitter
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
          ln -s $(pwd) ~/.local/share/nvim/site/pack/vendor/start
          nvim --headless -c "lua require('nvim-treesitter').setup {}" -c 'TSInstallSync all' -c 'q'
          
      - name: Run tests
        run: |
          nvim --version
          nvim --headless -c 'PlenaryBustedDirectory tests/'

  docs:
    runs-on: ubuntu-latest
    needs: tests
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: nvim-stormcaller
          version: "Neovim >= 0.8.0"
          demojify: true
          treesitter: true
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(build): auto-generate vimdoc"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

  release:
    name: release
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - docs
      - tests
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          package-name: nvim-stormcaller
      - uses: actions/checkout@v3
      - name: tag stable versions
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/google-github-actions/release-please-action.git"
          git tag -d stable || true
          git push origin :stable || true
          git tag -a stable -m "Last Stable Release"
          git push origin stable
